all:
  children:
    k8s_master:
      hosts:
        master:
          ansible_host: <IP_мастера>
    k8s_node:
      hosts:
        app:
          ansible_host: <IP_апп>
    monitoring:
      hosts:
        srv:
          ansible_host: <IP_srv>
