name: Docker CI/CD

on:
  push:
    tags:
      - 'vX.X.X'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t hub.docker.com/skillfactory/testapp:${GITHUB_SHA} .
      - name: Push Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push hub.docker.com/skillfactory/testapp:${GITHUB_SHA}
     
     - name: Deploy to Kubernetes via Helm
        run: |
          helm upgrade --install my-django-release ./charts/my-app \
            --namespace your-namespace \
            --set image.tag=${GITHUB_SHA}

